pipeline {
    agent none
     stages {
        stage('Compile') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
            steps {
                sh 'mvn -s settings.xml -B -DskipTests clean package'
            }
        }
        stage('build') {
            steps {
                sh 'docker build -t java:demo -f jenkins/dockerfile .'
            }
        }
    }
}
